#!/bin/bash

set -euo pipefail

export WORK="/tmp/go-fast-compile$(pwd | sed "s|^$GOPATH/src||")"
export GOBIN="$WORK"
export GOTOOLDIR=`go env GOTOOLDIR`

eval "$(
    go install -x -n "$@" 2>&1 \
        | grep -v -E "^(${GOTOOLDIR}/link|mv) " \
        | sed '/^CGO_LDFLAGS=/s/" "/ /g'
)"
